language: go

go:
- 1.14.4

script:
- make test

before_deploy:
- sudo apt-get install -y rpm ruby ruby-dev
- go get github.com/mitchellh/gox
- gem install fpm -v 1.11.0
- make gox-build
- make fpm-deb
- make fpm-rpm

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: VzFUZ1LemIo7KLoVv3r+gMEQJ9mj8om0YojWJ+bXFFsGCBHVBsAxn32j+6BTJq3pF2tkYCJmqVBjBF6QIFyW0pz+v2vVBCXoebXZWaS4KogThlT6uS7SqKUqfEGejofVAo6RZlY9LNKaPNEA4mE9TNMfDMvCaWlgQDyvi7i6hr0=
  file_glob: true
  file:
    - "*.{deb,rpm}"
    - "build/go-carbon-*"
  on:
    repo: go-graphite/go-carbon
    tags: true
