name: golangci-lint
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.45.2

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # TODO: --go 1.17 is added because of https://github.com/golangci/golangci-lint/issues/2649#issuecomment-1070528726
          args: --enable gofmt,goimports,gocritic --disable errcheck --go 1.17

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
